In [1]:
print("abc")

abc


In [37]:
import numpy as np
import pandas as pd
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
np.random.seed(0)

df=pd.DataFrame(np.random.randn(5,2),['A','B','C','D','E'],['X','Y'])

In [49]:
df

X         Y
A  1.764052  0.400157
B  0.978738  2.240893
C  1.867558 -0.977278
D  0.950088 -0.151357
E -0.103219  0.410599

In [54]:
df['X']['A']

1.764052345967664

In [58]:
df[['X','Y']]

X         Y
A  1.764052  0.400157
B  0.978738  2.240893
C  1.867558 -0.977278
D  0.950088 -0.151357
E -0.103219  0.410599

In [61]:
df['new']=df['X']+df['Y']

In [63]:
df

X         Y       new
A  1.764052  0.400157  2.164210
B  0.978738  2.240893  3.219631
C  1.867558 -0.977278  0.890280
D  0.950088 -0.151357  0.798731
E -0.103219  0.410599  0.307380

In [68]:
newdf=df.drop('new',axis=1)

In [70]:
newdf

X         Y
A  1.764052  0.400157
B  0.978738  2.240893
C  1.867558 -0.977278
D  0.950088 -0.151357
E -0.103219  0.410599

In [53]:
type(df['X'])

pandas.core.series.Series

In [25]:
np.random.seed(0)
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [12]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [3]:
i=1+1

In [5]:
print(i)

2


In [7]:
2*3

6

In [9]:
x=[1,2,3,4]

In [11]:
[num+1 for num in x]

[2, 3, 4, 5]

In [16]:
def num(abc):
    """
    MY DOC STRING
    """
    return abc

In [27]:
def cross2(num):
	return num*2

In [28]:
list(map(cross2,x))

[2, 4, 6, 8]

In [33]:
#lambda fns
t=lambda num: num*2

In [35]:
t(5)

10

In [38]:
list(map(lambda x:x*3,x))

[3, 6, 9, 12]

In [39]:
#using filter to filter out even elems
list(filter(lambda x:x%2==0,x))

[2, 4]

In [40]:
list1=[(1,2),(3,4)]

In [41]:
#tuple unpacking
for a,b in list1:
    print(a)

1
3
