In [2]:
import numpy as np

In [4]:
arr=np.arange(10)

In [9]:
#broadcasting
arr[5:]=100

In [11]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [14]:
arr2=arr.copy()

In [18]:
arr2[:]=99

In [20]:
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [22]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [24]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])